### ISSUE TITLE
/dev/alarm no longer works for setting the time

### ISSUE THREAD

**Issue by aecolley** [dschuermann/ntp-sync#23]
NTPSync silently fails to set the time on my SGH-T889 (a T-Mobile-dehanced Samsung Galaxy Note 2), creating log entries like this:

> E/DatabaseUtils( 3612): Writing exception to parcel
> E/DatabaseUtils( 3612): java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
> E/DatabaseUtils( 3612):   at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13175)
> E/DatabaseUtils( 3612):   at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2044)
> E/DatabaseUtils( 3612):   at com.android.providers.settings.SettingsProvider.callFromPackage(SettingsProvider.java:615)
> E/DatabaseUtils( 3612):   at android.content.ContentProvider$Transport.call(ContentProvider.java:279)
> E/DatabaseUtils( 3612):   at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:273)
> E/DatabaseUtils( 3612):   at android.os.Binder.execTransact(Binder.java:388)
> E/DatabaseUtils( 3612):   at dalvik.system.NativeStart.run(Native Method)
> W/ActivityManager( 3612): Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
> _[...]_
> D/SystemClock( 7840): Setting time of day to sec=1410443164
> D/SystemClock( 7840): Trying to open a file
> E/SystemClock( 7840): File Open Failed
> W/SystemClock( 7840): Unable to open alarm driver: Permission denied

The [SuperSU](https://play.google.com/store/apps/details?id=eu.chainfire.supersu) log clearly shows NTPSync successfully chmoding `/dev/alarm` to mode 666 and back. Oddly, there are no log entries with the tag `NTPSync` and I haven't been able to trigger the making of any Debug-level entries with `/data/local.prop`.

A [StackExchange answer](http://stackoverflow.com/questions/8739074/setting-system-time-of-rooted-phone#8752130) lays out the `/dev/alarm` technique, but goes on to claim that on newer Samsung firmwares, it doesn't work because of SELinux restrictions, and that use of `date` is needed.

So, how about some use of `date` if `setCurrentTimeMillis` fails? Or at least an error message.

**Comment by gsauthof** [comment]
It also doesn't work on recent Android devices, in general (e.g. Android 7, LineageOS). See also [garlicman's comment](https://stackoverflow.com/questions/8739074/setting-system-time-of-rooted-phone#comment64717816_8752130).

Logcat output from a Nexus 5 device with current LineageOS:

    10-31 11:11:44.285 23131 23195 E SystemClock: Unable to set RTC
    10-31 11:11:44.285 23131 23195 E SystemClock: java.lang.SecurityException: setTime: Neither user 10134 nor current process has android.permission.SET_TIME.
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.os.Parcel.readException(Parcel.java:1684)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.os.Parcel.readException(Parcel.java:1637)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.app.IAlarmManager$Stub$Proxy.setTime(IAlarmManager.java:235)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.os.SystemClock.setCurrentTimeMillis(SystemClock.java:150)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at org.sufficientlysecure.rootcommands.Toolbox$2.whileHavingPermissions(Toolbox.java:708)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at org.sufficientlysecure.rootcommands.Toolbox.withPermission(Toolbox.java:654)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at org.sufficientlysecure.rootcommands.Toolbox.withWritePermissions(Toolbox.java:672)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at org.sufficientlysecure.rootcommands.Toolbox.adjustSystemClock(Toolbox.java:704)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at org.ntpsync.util.Utils.setTime(Utils.java:82)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at org.ntpsync.service.NtpSyncService.onHandleIntent(NtpSyncService.java:163)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.os.Handler.dispatchMessage(Handler.java:102)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.os.Looper.loop(Looper.java:154)
    10-31 11:11:44.285 23131 23195 E SystemClock: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lemmy04** [comment]
so ... is there any solution to this?
I'm getting all sorts of problems with two factor authentification using time based keys with this...
